import argparse
import sys
import os
import glob
import json
import csv
from pathlib import Path
from typing import List, Dict, Any

# Ensure project root is in path
project_root = str(Path(__file__).resolve().parents[3])
if project_root not in sys.path:
    sys.path.append(project_root)

from src.collection.B.helpers import search_google, search_brave, search_mojeek

def merge_jsons_to_csv(json_root: str, output_csv: str):
    """
    Finds all JSONs generated by search helpers and merges them into a unified serp.csv.
    """
    print(f"Merging SERP json files from {json_root} into {output_csv}...")
    
    all_json = glob.glob(os.path.join(json_root, "**", "*.json"), recursive=True)
    if not all_json:
        print("No JSON files found to merge.")
        return
        
    os.makedirs(os.path.dirname(output_csv) or ".", exist_ok=True)
    
    fieldnames = [
        "search_engine",
        "query_id",
        "section",
        "search_term",
        "rank",
        "link",
        "file_name",
        "title",
        "snippet"
    ]
    
    file_exists = os.path.exists(output_csv)
    
    with open(output_csv, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        
        count = 0
        for jp in all_json:
            try:
                with open(jp, "r", encoding="utf-8") as jf:
                    data = json.load(jf)
            except Exception as e:
                print(f"Error reading {jp}: {e}")
                continue
                
            engine = data.get("engine", "unknown")
            query_id = data.get("id", "")
            section = data.get("section", "")
            search_term = data.get("query", "")
            items = data.get("items", [])
            
            for item in items:
                rank = item.get("rank", 0)
                file_name = f"{engine}_{query_id}_{rank}"
                
                row = {
                    "search_engine": engine,
                    "query_id": query_id,
                    "section": section,
                    "search_term": search_term,
                    "rank": rank,
                    "link": item.get("link", ""),
                    "file_name": file_name,
                    "title": item.get("title", ""),
                    "snippet": item.get("snippet", "")
                }
                writer.writerow(row)
                count += 1
                
    print(f"Merge complete. Wrote {count} rows to {output_csv}")

def main():
    parser = argparse.ArgumentParser(description="Collection Step B: Search SERP (Brave, Mojeek, Google)")
    parser.add_argument("--engine", type=str, choices=["google", "brave", "mojeek"], help="Which search engine scraper to run")
    parser.add_argument("--merge", action="store_true", help="Merge collected JSON files into a unified SERP CSV")
    
    # Common arguments
    parser.add_argument("--input", type=str, default="data/keywords.csv", help="Input keywords CSV")
    parser.add_argument("--output-json-dir", type=str, default="data/raw/serp_results", help="Output directory for raw JSONs")
    parser.add_argument("--output-csv", type=str, default="data/serp.csv", help="Output path for final serp.csv")
    parser.add_argument("--exceptions", type=str, default="data/exceptions_serp.csv", help="Exceptions CSV")
    parser.add_argument("--max-results", type=int, default=10, help="Max results per query")
    parser.add_argument("--overwrite", type=str, default="false", choices=["true", "false"])
    parser.add_argument("--sleep", type=float, default=1.1)
    parser.add_argument("--max-retries", type=int, default=5)
    parser.add_argument("--quote", type=str, default="false", choices=["true", "false"])

    # Engine specific defaults
    parser.add_argument("--country", type=str, default="US")
    parser.add_argument("--search-lang", type=str, default="en")
    parser.add_argument("--ui-lang", type=str, default="en-US")
    parser.add_argument("--safesearch", type=str, default="off")
    parser.add_argument("--hl", type=str, default="en")
    parser.add_argument("--gl", type=str, default="us")
    
    # Mojeek specific defaults
    parser.add_argument("--rb", type=str, default="US")
    parser.add_argument("--rbb", type=int, default=10)
    parser.add_argument("--lb", type=str, default="EN")
    parser.add_argument("--lbb", type=int, default=100)

    args = parser.parse_args()
    
    if not args.engine and not args.merge:
        parser.print_help()
        sys.exit(1)

    if args.engine == "google":
        cfg = search_google.Config(
            input_csv=args.input,
            output_dir=args.output_json_dir,
            exceptions_csv=args.exceptions,
            max_results=args.max_results,
            overwrite=(args.overwrite == "true"),
            sleep_s=args.sleep,
            max_retries=args.max_retries,
            hl=args.hl,
            gl=args.gl,
            safe=args.safesearch,
            quote=(args.quote == "true"),
        )
        search_google.run(cfg)

    elif args.engine == "brave":
        cfg = search_brave.Config(
            input_csv=args.input,
            output_dir=args.output_json_dir,
            exceptions_csv=args.exceptions,
            max_results=args.max_results,
            overwrite=(args.overwrite == "true"),
            sleep_s=args.sleep,
            max_retries=args.max_retries,
            country=args.country,
            search_lang=args.search_lang,
            ui_lang=args.ui_lang,
            safesearch=args.safesearch,
            quote=(args.quote == "true"),
        )
        search_brave.run(cfg)
        
    elif args.engine == "mojeek":
        cfg = search_mojeek.Config(
            input_csv=args.input,
            output_dir=args.output_json_dir,
            exceptions_csv=args.exceptions,
            max_results=args.max_results,
            overwrite=(args.overwrite == "true"),
            sleep_s=args.sleep,
            max_retries=args.max_retries,
            rb=args.rb,
            rbb=args.rbb,
            lb=args.lb,
            lbb=args.lbb,
            safe=1 if args.safesearch != "off" else 0,
            quote=(args.quote == "true"),
        )
        search_mojeek.run(cfg)

    if args.merge:
        merge_jsons_to_csv(args.output_json_dir, args.output_csv)

if __name__ == "__main__":
    main()
